kind: pipeline
type: docker
name: translations and contributors

steps:
- name: install dependencies
  image: node
  commands:
  - npm install
- name: import translations
  image: node
  commands:
  - cd ci/
  - node import_translations.js
  environment:
    POEDITOR_API_TOKEN:
      from_secret: POEDITOR_API_TOKEN
- name: convert to fastlane files
  image: node
  commands:
  - cd fastlane/
  - node metadata/android/poeditor2fastlane.js
- name: create contributors.md
  image: node
  commands:
  - node pull_contributors.js
  environment:
    POEDITOR_API_TOKEN:
      from_secret: POEDITOR_API_TOKEN
- name: report 
  image: bitnami/git
  commands:
  - echo "Git status now:"
  - git status
  # Do not push package-lock.json
  - git restore package-lock.json
- name: push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:JonasBernard/FakeStandby.git
    ssh_key:
      from_secret: GH_SSH_KEY
    force: false
    commit: true
    commit_message: "Auto-imported translations from PoEditor and updated CONTRIBUTING.MD"
    author_name: Drone Pipeline
trigger:
  event:
    include:
    - promote
    - custom