theme: jekyll-theme-cayman
description: >-
  FakeStandby is an Android app to turn off your
  screen while keeping apps running.
title: "FakeStandby"
# logo: /path/to/logo.png
show_downloads: false
timezone: Europe/Berlin
lang: en
github_username: JonasBernard
email: public.jbernard@web.de
domain: jonasbernard.github.io
url: "https://jonasbernard.github.io/FakeStandby"
f-droid_url: "https://f-droid.org/packages/android.jonas.fakestandby/"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-include-cache
