name: Android CI

on:
  push:
    tags:
     - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_CONFIG > app/google-services.json
    
    - name: Build with Gradle
      run: ./gradlew assembleAdfreeRelease --stacktrace

    - name: Sign Adfree APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/adfree/release
        signingKeyBase64: ${{ secrets.DEPLOY_SIGN_KEY_JKS_BASE64 }}
        alias: ${{ secrets.DEPLOY_SIGN_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.DEPLOY_SIGN_KEY_JKS_PASSWORD }}
        keyPassword: ${{ secrets.DEPLOY_SIGN_KEY_PASSWORD }}
        
    - name: Create Release on GitHub
      uses: actions/create-release@v1.1.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.GITHUB_REF }}
        release_name: Auto-Release of Adfree APK ${{ github.GITHUB_REF }} 
        body: Autogenerated and signed APK file for the adfree build variant.
        body_path: app/build/outputs/apk/adfree/release/output-metadata.json
        draft: false
        prerelease: false
