name: build

on:
  push:
    tags:
     - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      signedReleaseFile: ${{ steps.sign-apk.outputs.signedReleaseFile }}
      releaseVersion: ${{ steps.get-version.outputs.version }}

    steps:
    - name: Get the version
      id: get-version
      run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
          
    - uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: echo $FIREBASE_CONFIG > app/google-services.json
    
    - name: Build with Gradle
      run: ./gradlew assembleAdfreeRelease --stacktrace

    - name: Sign Adfree APK
      id: sign-apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/adfree/release
        signingKeyBase64: ${{ secrets.DEPLOY_SIGN_KEY_JKS_BASE64 }}
        alias: ${{ secrets.DEPLOY_SIGN_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.DEPLOY_SIGN_KEY_JKS_PASSWORD }}
        keyPassword: ${{ secrets.DEPLOY_SIGN_KEY_PASSWORD }}
        
  gh-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release on GitHub
      id: create-release
      uses: actions/create-release@v1.1.3
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Auto-Release of Adfree APK ${{ github.GITHUB_REF }} 
        body: Autogenerated and signed APK file for the adfree build variant.
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ${{ needs.build.outputs.signedReleaseFile }}
        asset_name: FakeStandby_${{ needs.build.outputs.releaseVersion }}_adfree_release.apk
        asset_content_type: application/vnd.android.package-archive
        
  play-store-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Create whats-new files
      id: whats-new
      run: cd ci && node generate_whatsnew_files.js
      
    - name: Create draft release on Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
        packageName: android.jonas.fakestandby
        releaseFile: ${{ needs.build.outputs.signedReleaseFile }}
        releaseName: ${{ needs.build.outputs.releaseVersion }}
        track: production
        status: draft
        whatsNewDirectory: whatsnew/
        mappingFile: app/build/outputs/mapping/release/mapping.txt
